---
swagger: "2.0"
info:
  description: "Swagger API definition for the suppliers apis"
  version: "0.0.2"
  title: "APIs to interact with suppliers external systems"
host: suppliers.dekt-brownfield.io
basePath: "/v1"
tags:
- name: "Data collection"
  description: "Data collection (read-only) APIs"
- name: "Data manipulation"
  description: "Data manipulation (write) APIs"
schemes:
- "https"
paths:
  /list-suppliers:
    get:
      tags:
      - "Data collection"
      summary: "List available suppliers"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful data collection"
        400:
          description: "Invalid candidate identifier"
  /add-supplier/{supplierID}:
    post:
      tags:
      - "Data manipulation"
      summary: "Add a new supplier"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "supplierID"
        in: "path"
        description: "ID of supplier to update data for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful data collection"
        400:
          description: "Invalid candidate identifier"