apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: dekt4pets-dev-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: dekt4pets-dev.tanzu.dekt.io
      http: 
       paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: dekt4pets-gateway-dev
             port:
               number: 80