apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: acc-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: acc.SUB-DOMAIN.DOMAIN
      http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: acc-ui-server
              port:
                number: 80