apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: api-portal-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx 
spec: 
  rules: 
    - host: api-portal.SUB-DOMAIN.DOMAIN
      http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-portal-server
              port:
                number: 8080