apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: accelerator-system

resources:
  - backend-api.yaml
  - frontend-ux.yaml
  - web-function.yaml
  - event-driven.yaml
  - data-transfer.yaml
  - machine-learning.yaml
  - microservices-supplychain.yaml
  - datatransform-supplychain.yaml
